export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS';
export const DISLIKE_ARTICLE_SUCCESS = 'DISLIKE_ARTICLE_SUCCESS';
export const ARTICLE_LIKE_STATUS = 'ARTICLE_LIKE_STATUS';
export const ARTICLE_DISLIKE_STATUS = 'ARTICLE_DISLIKE_STATUS';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const ARTICLE_LIKE_COUNT = 'ARTICLE_LIKE_COUNT';
