const actionTypes = {
  FACEBOOK_SUCCESS: 'FACEBOOK_SUCCESS',
  FACEBOOK_FAIL: 'FACEBOOK_FAIL',
  GOOGLE_SUCCESS: 'GOOGLE_SUCCESS',
  GOOGLE_FAIL: 'GOOGLE_FAIL',
  FOLLOW_USER: 'FOLLOW_USER',
  UNFOLLOW_USER: 'UNFOLLOW_USER',
  GET_FOLLOWING: 'GET_FOLLOWING',
  GET_FOLLOWERS: 'GET_FOLLOWERS'
};

export default actionTypes;
