export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL';
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const EDIT_ARTICLE_FAIL = 'EDIT_ARTICLE_FAIL';
export const MY_ARTICLES_SUCCESS = 'MY_ARTICLES_SUCCESS';
export const MY_ARTICLES_FAIL = 'MY_ARTICLES_FAIL';
