const COMMENTS = {
    COMMENTS_ERRORS: 'COMMENTS_ERRORS',
    POST_COMMENT: 'POST_COMMENT',
    GET_COMMENTS_ERRORS: 'GET_COMMENTS_ERRORS',
    GET_COMMENT: 'GET_COMMENT',
    UPDATE_COMMENTS_ERRORS: 'UPDATE_COMMENTS_ERRORS',
    UPDATE_COMMENT: 'UPDATE_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    };
  
    export default COMMENTS;